### ISSUE TITLE
Segfault cefcapi.out Ubuntu 14.04

### ISSUE THREAD

**Issue by diags50** [cztomczak/cefcapi#8]
Hi 
When i execute cefcapi.out i get a segfault.
```
./cefcapi.out 

Process args: none (Main process)

initialize_cef_app
initialize_cef_base_ref_counted
cef_base_ref_counted_t.size = 72
cef_execute_process, argc=1
cef_base_ref_counted_t.add_ref
cef_base_ref_counted_t.release
cef_initialize
on_before_command_line_processing
on_register_custom_schemes
get_browser_process_handler

Process args: --type=zygote --no-sandbox --lang=en-US --log-file=debug.log --log-severity=warning 

initialize_cef_app
initialize_cef_base_ref_counted
cef_base_ref_counted_t.size = 72
cef_execute_process, argc=6
cef_base_ref_counted_t.add_ref
cef_base_ref_counted_t.release
on_before_command_line_processing
on_register_custom_schemes
get_resource_bundle_handler
Erreur de segmentation (core dumped)
```

What can be the cause of this segfault ?

PS: See below the result with gdb

```
gdb ./cefcapi.out 
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./cefcapi.out...done.
(gdb) r
Starting program: cefcapi.out 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Process args: none (Main process)

initialize_cef_app
initialize_cef_base_ref_counted
cef_base_ref_counted_t.size = 72
cef_execute_process, argc=1
cef_base_ref_counted_t.add_ref
cef_base_ref_counted_t.release
cef_initialize
on_before_command_line_processing
on_register_custom_schemes
[New Thread 0x7fffe5b92700 (LWP 25155)]
get_browser_process_handler

Process args: --type=zygote --no-sandbox --lang=en-US --log-file=debug.log --log-severity=warning 

initialize_cef_app
initialize_cef_base_ref_counted
cef_base_ref_counted_t.size = 72
cef_execute_process, argc=6
cef_base_ref_counted_t.add_ref
cef_base_ref_counted_t.release
on_before_command_line_processing
on_register_custom_schemes
[New Thread 0x7fffe5391700 (LWP 25161)]
[New Thread 0x7fffe4b90700 (LWP 25162)]
[New Thread 0x7fffd7fff700 (LWP 25163)]
[New Thread 0x7fffd77fe700 (LWP 25164)]
[New Thread 0x7fffd6ffd700 (LWP 25165)]
[New Thread 0x7fffd67fc700 (LWP 25166)]
[New Thread 0x7fffd5ffb700 (LWP 25167)]
[New Thread 0x7fffd57fa700 (LWP 25168)]
[New Thread 0x7fffd4ff9700 (LWP 25169)]
[New Thread 0x7fffb7fff700 (LWP 25170)]
[New Thread 0x7fffb77fe700 (LWP 25171)]
[New Thread 0x7fffb6ffd700 (LWP 25172)]
[New Thread 0x7fffb67fc700 (LWP 25173)]
[New Thread 0x7fffb5ffb700 (LWP 25174)]
[New Thread 0x7fffb57fa700 (LWP 25175)]
get_resource_bundle_handler

Program received signal SIGSEGV, Segmentation fault.
GetAsDictionary () at ../../base/values.cc:341
341	../../base/values.cc: Aucun fichier ou dossier de ce type.
(gdb) bt
#0  GetAsDictionary () at ../../base/values.cc:341
#1  0x00007ffff17df649 in AddServiceManifest () at ../../content/browser/service_manager/service_manager_context.cc:138
#2  0x00007ffff17de641 in ServiceManagerContext () at ../../content/browser/service_manager/service_manager_context.cc:272
#3  0x00007ffff15e367e in InitializeMojo () at ../../content/browser/browser_main_loop.cc:1695
#4  0x00007ffff15e25e4 in BrowserThreadsStarted () at ../../content/browser/browser_main_loop.cc:1411
#5  0x00007ffff186baf6 in Run () at ../../base/callback.h:85
#6  RunAllTasksNow () at ../../content/browser/startup_task_runner.cc:45
#7  0x00007ffff15e160b in CreateStartupTasks () at ../../content/browser/browser_main_loop.cc:974
#8  0x00007ffff15dce51 in Initialize () at ../../content/browser/browser_main_runner.cc:125
#9  0x00007ffff24c7d56 in RunProcess () at ../../cef/libcef/common/main_delegate.cc:562
#10 0x00007ffff2426d27 in RunNamedProcessTypeMain () at ../../content/app/content_main_runner.cc:478
#11 0x00007ffff242748c in Run () at ../../content/app/content_main_runner.cc:836
#12 0x00007ffff2454aa2 in Initialize () at ../../cef/libcef/browser/context.cc:384
#13 0x00007ffff24547e7 in CefInitialize () at ../../cef/libcef/browser/context.cc:222
#14 0x00007ffff11383d4 in cef_initialize () at ../../cef/libcef_dll/libcef_dll.cc:222
#15 0x0000000000401a91 in main (argc=1, argv=0x7fffffffdc88) at examples/main_linux.c:76
(gdb) info thread
  Id   Target Id         Frame 
  17   Thread 0x7fffb57fa700 (LWP 25175) "Chrome_IOThread" 0x00007fffef68ea13 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  16   Thread 0x7fffb5ffb700 (LWP 25174) "Chrome_CacheThr" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  15   Thread 0x7fffb67fc700 (LWP 25173) "Chrome_ProcessL" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  14   Thread 0x7fffb6ffd700 (LWP 25172) "Chrome_FileUser" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  13   Thread 0x7fffb77fe700 (LWP 25171) "Chrome_FileThre" 0x00007fffef68ea13 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  12   Thread 0x7fffb7fff700 (LWP 25170) "Chrome_DBThread" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  11   Thread 0x7fffd4ff9700 (LWP 25169) "TaskSchedulerFo" pthread_cond_timedwait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  10   Thread 0x7fffd57fa700 (LWP 25168) "TaskSchedulerFo" pthread_cond_timedwait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  9    Thread 0x7fffd5ffb700 (LWP 25167) "TaskSchedulerBa" pthread_cond_timedwait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  8    Thread 0x7fffd67fc700 (LWP 25166) "TaskSchedulerBa" pthread_cond_timedwait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  7    Thread 0x7fffd6ffd700 (LWP 25165) "TaskSchedulerSe" 0x00007fffef68ea13 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  6    Thread 0x7fffd77fe700 (LWP 25164) "WorkerPool/2516" pthread_cond_timedwait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  5    Thread 0x7fffd7fff700 (LWP 25163) "WorkerPool/2516" pthread_cond_timedwait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  4    Thread 0x7fffe4b90700 (LWP 25162) "inotify_reader" 0x00007fffef685c53 in select () at ../sysdeps/unix/syscall-template.S:81
  3    Thread 0x7fffe5391700 (LWP 25161) "NetworkChangeNo" 0x00007fffef68ea13 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  2    Thread 0x7fffe5b92700 (LWP 25155) "sandbox_ipc_thr" 0x00007fffef680fdd in poll () at ../sysdeps/unix/syscall-template.S:81
* 1    Thread 0x7ffff7faea00 (LWP 25041) "cefcapi.out" GetAsDictionary () at ../../base/values.cc:341
```

**Comment by cztomczak** [comment]
Have you made any modifications to the example?
Have you copied all necessary CEF resources to the Release directory?

**Comment by cztomczak** [comment]
Closing since no feedback from the reporter.
